name: Run Flask App with ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Start Flask App
        env:
          FLASK_APP: app.py  # เปลี่ยนชื่อไฟล์ให้ตรงกับชื่อ Flask app ของคุณ
        run: |
          nohup python -m flask run --host=0.0.0.0 --port=5000 &
      - name: Install ngrok
        run: |
          curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip -d /home/runner/ngrok
          export PATH="/home/runner/ngrok:$PATH"

      - name: Start ngrok
        run: |
          nohup ./ngrok http 5000 > /dev/null &
          sleep 5
      
      - name: Get ngrok URL
        run: |
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
